### ISSUE TITLE
"Cannot Invoke String.toUpperCase()..." error compiling simple WiFitest example .spin2 file

### ISSUE THREAD

**Issue by dgately** [maccasoft/spin-tools#8]
Getting 2 errors in this example code. Error shows up on an 'else' line in the code, in two places.

`				if c > "z" or c < " "
					ser.fstr1(@"<%x>", c)
					if c == 13
						ser.tx(c)
						ser.tx(10)
				else                                         <== error shows up here!
					ser.tx(c)
`

Image of the error:
![CompileError](https://github.com/maccasoft/spin-tools/assets/3009364/d0e6e160-3f0a-4714-9cfd-ba1d10061239)

Attached archive of the project:
[testWiFi240 - Archive [Date 2024.03.20 Time 12.17].zip](https://github.com/maccasoft/spin-tools/files/14671581/testWiFi240.-.Archive.Date.2024.03.20.Time.12.17.zip)

Setup:
Apple Silicon MacBook Pro
MacOS version: 14.4
Spin Tools IDE version: 034.2

**Comment by maccasoft** [comment]
Seems the issue is related to the TAB characters on those lines, for some reasons the parser gets confused (you can see the block lines are not drawn or not correct).
You can "re-tab" the lines to fix it, or convert the TABs to spaces with an external program or editor.
The editor should automatically convert TABs to spaces, I don't know how they were inserted.

**Comment by dgately** [comment]
Ah... I used SubEthaEdit to 'detab' the code and resaved it. Compiles correctly now! Thx
